package com.example.spring_boot_project_api.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * Holds the per-user TOTP material. Secrets are persisted exclusively as AES-GCM
 * ciphertext ({@code *_enc} columns) - never in plaintext.
 *
 * <p>{@code secretEnc} is populated once 2FA is confirmed/enabled;
 * {@code pendingSecretEnc} holds a staged secret generated by {@code POST /auth/2fa/setup}
 * until the user proves possession of it via {@code POST /auth/2fa/enable}.</p>
 */
@Entity
@Table(name = "user_two_factor_auth")
@Getter
@Setter
@Builder
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor
public class TwoFactorAuth {

	@Id
	@Column(name = "user_id", nullable = false)
	private Long userId;

	@Column(name = "secret_enc", length = 512)
	private String secretEnc;

	@Column(name = "pending_secret_enc", length = 512)
	private String pendingSecretEnc;

	@Column(name = "updated_at", nullable = false)
	private LocalDateTime updatedAt;

	@PreUpdate
	void onUpdate() {
		updatedAt = LocalDateTime.now();
	}
}
